
PKG_DIR :=org/apache/log4j/xml
DEPTH   :=../../../..
JSOURCES:=DOMConfigurator.java\
	XMLLayout.java\


SUBDIRS :=eu.stamp_project.evocrash examples

# include master-rule file
include $(DEPTH)/make/make.inc






